---
- name: Adding Docker key to keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: Adding Docker repository to apt sources
  apt_repository:
    repo: 'deb http://get.docker.com/ubuntu docker main'

- name: Installing common packages
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - python-pip
    - python-mysqldb
    - lxc-docker

- name: Setting insecure-registry
  copy:
    content: 'DOCKER_OPTS="--insecure-registry {{ docker_registry }}"\n'
    dest: '/etc/default/docker'
  notify: restart docker
