---
- name: Adding Docker key to keyserver
  apt_key:
    url: https://get.docker.io/gpg

- name: Adding Docker repository to apt sources
  apt_repository:
    repo: 'deb http://get.docker.com/ubuntu docker main'

- name: Installing common packages
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - python-pip
    - lxc-docker

- name: Setting insecure-registry
  copy:
    content: 'DOCKER_OPTS="--insecure-registry {{ docker_registry }}"\n'
    dest: '/etc/default/docker'
  notify: restart docker
