---
- include: install_packages-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Upgrade pip
  pip:
    name: pip
    state: latest

- name: Installing docker-py
  pip:
    name: docker-py

- name: Create yaodu group
  group:
    name: yaodu
    gid: 42424

- name: Create yaodu user
  user:
    name: yaodu
    group: yaodu
    createhome: no
    uid: 42424
