---
- name: Creating temp file on localhost
  local_action: shell echo 'None' > /tmp/yaodu_mariadb_cluster
  register: status
  changed_when: False
  failed_when: status.rc != 0
  always_run: True
  run_once: True

- name: Checking if a previous cluster exists
  stat:
    path: "/opt/yaodu/mariadb/data/grastate.dat"
  register: mysql

- name: Writing hostname of host with existing cluster files to temp file
  local_action: shell echo "{{ ansible_hostname }}" > /tmp/yaodu_mariadb_cluster
  register: status
  changed_when: False
  failed_when: status.rc != 0
  always_run: True
  when: mysql.stat.exists

- name: Registering host from temp file
  set_fact:
    delegate_host: "{{ lookup('file', '/tmp/yaodu_mariadb_cluster') }}"

- name: Cleaning up temp file on localhost
  local_action: shell rm /tmp/yaodu_mariadb_cluster
  register: status
  changed_when: False
  failed_when: status.rc != 0
  always_run: True
  run_once: True

- include: bootstrap.yml
  when: delegate_host == 'None' and inventory_hostname == groups['database'][0]
