---
- name: Adding MariaDB key to keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB

- name: Adding MariaDB repository to apt sources
  apt_repository:
    repo: 'deb http://nyc2.mirrors.digitalocean.com/mariadb/repo/5.5/ubuntu trusty main'

- name: Installing MariaDB client packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb-client
