---
- name: Starting Mariadb Database
  docker:
    name: "mariadb"
    image: "{{ docker_registry }}/yaodu/mariadb"
    state: "running"
    net: "host"
    volumes: "/opt/yaodu/mariadb/galera.cnf:/etc/mysql/conf.d/galera.cnf,/opt/yaodu/mariadb/data/:/var/lib/mysql/"
