neutronopenvswitchagent:
  image: "{{ docker_registry }}/yaodu/neutron"
  privileged: true
  net: "host"
  environment:
    SERVICE: openvswitch-agent
    BRIDGE_MAPPING: br-ex
    BRIDGE_INTERFACE: br-ext
  volumes:
    - /run/:/run/
    - /opt/yaodu/neutron/:/etc/neutron/:ro
  entrypoint: /entrypoint.sh
