openvswitchdb:
  image: "{{ docker_registry }}/yaodu/neutron"
  environment:
    SERVICE: db
  volumes:
    - /run/:/run/
  entrypoint: /entrypoint.sh

openvswitchswitch:
  image: "{{ docker_registry }}/yaodu/neutron"
  privileged: true
  net: "host"
  environment:
    SERVICE: switch
  volumes_from:
    - db
  volumes:
    - /run/:/run/
    - /lib/modules/:/lib/modules/:ro
  entrypoint: /entrypoint.sh
