FROM		{{ docker_registry }}/yaodu/openstack_common
MAINTAINER	Sam Yaple <sam@yaple.net>

ADD             {{ container }}.tar.gz /opt/yaodu/
RUN             ln -s /opt/yaodu/{{ container }}-*/ /opt/yaodu/{{ container }}

RUN             apt-get install -y --no-install-recommends python-ceph

RUN             cd /opt/yaodu/requirements/ && python update.py /opt/yaodu/{{ container }}/
RUN             cd /opt/yaodu/{{ container }}/ && pip install .

ADD             entrypoint.sh /entrypoint.sh
RUN             chmod +x /entrypoint.sh

RUN             groupadd -g 42424 {{ container }} && useradd -u 42424 -g {{ container }} -s /sbin/nologin -c "{{ container }} user" {{ container }}
RUN             mkdir -p /etc/ceph/ /etc/{{ container }}/ /var/log/{{ container }}/ /var/lib/{{ container }}/
RUN             cp -a /opt/yaodu/glance/etc/*.json /opt/yaodu/glance/etc/*.ini /opt/yaodu/glance/etc/metadefs/ /etc/glance/
RUN             chown -R {{ container }}: /etc/ceph/ /var/log/{{ container }}/ /var/lib/{{ container }}/ /etc/{{ container }}/

USER            {{ container }}
WORKDIR         /var/lib/{{ container }}
ENTRYPOINT      ["/entrypoint.sh"]
