FROM		{{ docker_registry }}/yaodu/openstack_common
MAINTAINER	Sam Yaple <sam@yaple.net>

RUN		apt-get install -y glance && \
                apt-get clean

RUN             mv /etc/glance/ /etc/glance.org/

ADD             entrypoint.sh /entrypoint.sh
RUN             chmod +x /entrypoint.sh

USER            glance
WORKDIR         /var/lib/glance
