---
- include: container_pull.yml

- name: Ensuring /opt/yaodu/glance/ exists
  file:
    path: /opt/yaodu/glance/
    state: directory
    group: yaodu
    owner: yaodu

- name: Copying Glance configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    group: yaodu
    owner: yaodu
  with_items:
    - { src: "glance-api.conf.j2" , dest: "/opt/yaodu/glance/glance-api.conf" }
    - { src: "glance-registry.conf.j2" , dest: "/opt/yaodu/glance/glance-registry.conf" }

- name: Generating environment string
  docker_env_builder:
    config_files:
      - { src: '/opt/yaodu/glance/glance-api.conf', dest: '/etc/glance/glance-api.conf' }
  register: glance_api

- name: Generating environment string
  docker_env_builder:
    config_files:
      - { src: '/opt/yaodu/glance/glance-registry.conf', dest: '/etc/glance/glance-registry.conf' }
  register: glance_registry

- name: Creating keystone user glance
  keystone:
    command: "ensure_user"
    tenant_name: "service"
    user_name: "glance"
    password: "{{ keystone_glance_password }}"
    description: "Glance User"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Adding keystone role admin to user glance
  keystone:
    command: "ensure_user_role"
    user_name: "glance"
    tenant_name: "service"
    role_name: "admin"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Creating keystone service glance
  keystone:
    command: "ensure_service"
    service_name: "glance"
    service_type: "image"
    description: "Image Service"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Creating keystone endpoint glance
  keystone:
    command: "ensure_endpoint"
    region_name: "regionOne"
    service_name: "glance"
    service_type: "image"
    publicurl: "http://{{ yaodu_api_vip }}:9292"
    adminurl: "http://{{ yaodu_api_vip }}:9292"
    internalurl: "http://{{ yaodu_api_vip }}:9292"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Generating environment string
  docker_env_builder:
    config_files:
      - { src: '/opt/yaodu/glance/glance-api.conf', dest: '/etc/glance/glance-api.conf' }
      - { src: '/opt/yaodu/glance/glance-registry.conf', dest: '/etc/glance/glance-registry.conf' }
  register: docker_vars

- include: bootstrap.yml

- include: start.yml
