---
- name: Merge dicts
  merge_dict:
    initial: "{{ docker_vars.env }}"
    update:
      SERVICE: 'registry'
  register: env

- name: Starting Glance Registry
  docker:
    docker_api_version: '1.18'
    name: "glance-registry"
    image: "{{ docker_registry }}/yaodu/glance"
    state: "running"
    net: "host"
    env: "{{ env.out }}"

- name: Merge dicts
  merge_dict:
    initial: "{{ docker_vars.env }}"
    update:
      SERVICE: 'api'
  register: env

- name: Starting Glance Api
  docker:
    docker_api_version: '1.18'
    name: "glance-api"
    image: "{{ docker_registry }}/yaodu/glance"
    state: "running"
    net: "host"
    volumes: "/opt/yaodu/ceph/{{ ceph_cluster_name }}.client.glance.keyring:/etc/ceph/{{ ceph_cluster_name }}.client.glance.keyring:ro,/opt/yaodu/ceph/{{ ceph_cluster_name }}.conf:/etc/ceph/{{ ceph_cluster_name }}.conf:ro"
    env: "{{ env.out }}"
