---
- name: Starting Glance Registry
  docker:
    name: "glance-registry"
    image: "{{ docker_registry }}/yaodu/glance"
    state: "running"
    net: "host"
    env: "{{ glance_registry.env }},SERVICE=registry"

- name: Starting Glance Api
  docker:
    name: "glance-api"
    image: "{{ docker_registry }}/yaodu/glance"
    state: "running"
    net: "host"
    volumes: "/opt/yaodu/ceph/{{ ceph_cluster_name }}.client.glance.keyring:/etc/ceph/{{ ceph_cluster_name }}.client.glance.keyring:ro,/opt/yaodu/ceph/{{ ceph_cluster_name }}.conf:/etc/ceph/{{ ceph_cluster_name }}.conf:ro"
    env: "{{ glance_api.env }},SERVICE=api"
