---
- name: Creating temp file on localhost
  local_action: shell echo 'None' > /tmp/yaodu_ceph_cluster
  always_run: True
  changed_when: False
  run_once: True

- name: Checking if a previous cluster exists
  stat:
    path: "/etc/ceph/{{ ceph_cluster_name }}.monmap"
  register: monmap

- name: Writing hostname of host with existing cluster files to temp file
  local_action: shell echo "{{ ansible_hostname }}" > /tmp/yaodu_ceph_cluster
  always_run: True
  changed_when: False
  when: monmap.stat.exists

- name: Registering host from tempfile
  set_fact:
    delegate_host: "{{ lookup('file', '/tmp/yaodu_ceph_cluster') }}"

- name: Cleaning up temp file on localhost
  local_action: shell rm /tmp/yaodu_ceph_cluster
  always_run: True
  changed_when: False
  run_once: True

- include: bootstrap.yml
  when: delegate_host == 'None'
  run_once: True

- name: Pulling keyrings from monitor
  bslurp:
     src: "{{ item }}"
  with_items:
     - "/etc/ceph/{{ ceph_cluster_name }}.client.admin.keyring"
     - "/etc/ceph/{{ ceph_cluster_name }}.mon.keyring"
     - "/etc/ceph/{{ ceph_cluster_name }}.monmap"
  register: ceph_files
  delegate_to: "{{ delegate_host }}"
  run_once: True

- name: Pushing keyrings to monitors
  bslurp:
    src: "{{ item.content }}"
    dest: "{{ item.source }}"
    mode: "{{ item.mode }}"
    sha_hash: "{{ item.sha_hash }}"
  with_items: ceph_files.results

- include: stop_start.yml
  serial: 1
