---
- include: container_pull.yml

- name: Ensuring /opt/yaodu/keystone/ exists
  file:
    path: /opt/yaodu/keystone/
    state: directory
    group: yaodu
    owner: yaodu

- name: Copying keystone.conf
  template:
    src: keystone.conf.j2
    dest: "/opt/yaodu/keystone/keystone.conf"
    mode: 0644

- name: Generating environment string
  docker_env_builder:
    config_files:
      - { src: '/opt/yaodu/keystone/keystone.conf', dest: '/etc/keystone/keystone.conf' }
  register: docker_vars

- include: bootstrap.yml

- include: start.yml

- name: Creating keystone tenant admin
  keystone:
    command: "ensure_tenant"
    tenant_name: "admin"
    description: "Admin Tenant"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    token: "{{ keystone_admin_token }}"
  run_once: True

- name: Creating keystone user admin
  keystone:
    command: "ensure_user"
    tenant_name: "admin"
    user_name: "admin"
    password: "{{ keystone_admin_password }}"
    description: "Admin User"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    token: "{{ keystone_admin_token }}"
  run_once: True

- name: Creating keystone role admin
  keystone:
    command: "ensure_role"
    role_name: "admin"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    token: "{{ keystone_admin_token }}"
  run_once: True

- name: Adding keystone role admin to user admin
  keystone:
    command: "ensure_user_role"
    user_name: "admin"
    tenant_name: "admin"
    role_name: "admin"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    token: "{{ keystone_admin_token }}"
  run_once: True

- name: Creating keystone tenant service
  keystone:
    command: "ensure_tenant"
    tenant_name: "service"
    description: "Service Tenant"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    token: "{{ keystone_admin_token }}"
  run_once: True

- name: Creating keystone service identity
  keystone:
    command: "ensure_service"
    service_name: "keystone"
    service_type: "identity"
    description: "Identity Service"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    token: "{{ keystone_admin_token }}"
  run_once: True

- name: Creating keystone endpoint keystone
  keystone:
    command: "ensure_endpoint"
    region_name: "regionOne"
    service_name: "keystone"
    service_type: "identity"
    publicurl: "http://{{ yaodu_api_vip }}:5000/v2.0"
    internalurl: "http://{{ yaodu_api_vip }}:5000/v2.0"
    adminurl: "http://{{ yaodu_api_vip }}:35357/v2.0"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    token: "{{ keystone_admin_token }}"
  run_once: True
