---
- name: Starting Keystone
  docker:
    docker_api_version: '1.18'
    name: "keystone"
    image: "{{ docker_registry }}/yaodu/keystone"
    state: "running"
    net: "host"
    env: "{{ docker_vars.env }}"

- name: Waiting for service to be available
  local_action: command sleep 5
