---
- name: Pulling admin keyring
  bslurp:
     src: "{{ item }}"
  with_items:
     - "/opt/yaodu/ceph/{{ ceph_cluster_name }}.client.admin.keyring"
  register: ceph_files
  delegate_to: "{{ delegate_host }}"
  run_once: True

- name: Pushing admin keyring
  include: configs_push.yml

- name: Pulling monitor map and keyring
  bslurp:
     src: "{{ item }}"
  with_items:
     - "/opt/yaodu/ceph/{{ ceph_cluster_name }}.mon.keyring"
     - "/opt/yaodu/ceph/{{ ceph_cluster_name }}.monmap"
  register: ceph_files
  delegate_to: "{{ delegate_host }}"
  run_once: True

- name: Pushing monitor map and keyring
  include: configs_push.yml
  when: inventory_hostname in groups['ceph-mon']
