---
- name: Adding Ceph key to keyserver
  apt_key:
    url: "https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc"

- name: Adding Ceph repository to apt sources
  apt_repository:
    repo: 'deb http://ceph.com/debian-{{ ceph_release }}/ trusty main'

- name: Installing common packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ceph-common
