---
- include: install_packages-ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and
        inventory_hostname in groups['management']

- include: container_pull.yml
  when: inventory_hostname in groups['ceph-all']
  vars:
    container: ceph

- name: Ensuring /etc/ceph/ exists
  file:
    path: /etc/ceph/
    state: directory
    group: yaodu
    owner: yaodu

- name: Copying Ceph cluster conf
  template:
    src: ceph.conf.j2
    dest: "/etc/ceph/{{ ceph_cluster_name }}.conf"
    mode: 0644

- include: check_for_existing_cluster.yml
  when: inventory_hostname in groups['ceph-mon']

- include: configs_sync.yml

- include: start_mon.yml
  when: inventory_hostname in groups['ceph-mon']

- include: bootstrap_osd.yml

- include: start_osd.yml
  when: inventory_hostname in groups['ceph-osd']
