---
- include: install_packages-ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and
        inventory_hostname in groups['management']

- include: container_pull.yml
  when: inventory_hostname in groups['ceph-all']
  vars:
    container: ceph

- name: Ensuring /etc/ceph/ exists
  file:
    path: /etc/ceph/
    state: directory
    group: yaodu
    owner: yaodu

- name: Copying Ceph cluster conf
  template:
    src: ceph.conf.j2
    dest: "/etc/ceph/{{ ceph_cluster_name }}.conf"
    mode: 0644

- include: check_for_existing_cluster.yml
  when: inventory_hostname in groups['ceph-mon']

- include: configs_sync.yml

- include: start_mon.yml
  when: inventory_hostname in groups['ceph-mon']

- include: bootstrap_osd.yml

- include: start_osd.yml
  when: inventory_hostname in groups['ceph-osd']

- name: Creating initial pools and keys
  shell: ceph osd pool create volumes 128; ceph osd pool create images 128; ceph osd pool create vms 128; ceph auth get-or-create client.cinder mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=volumes, allow rwx pool=vms, allow rx pool=images'; ceph auth get-or-create client.glance mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=images'
  run_once: true
