---
- name: Mounting volumes
  mount:
    src: "UUID={{ item['fs_uuid'] }}"
    fstype: xfs
    state: mounted
    name: "/var/lib/ceph/osd/{{ item['fs_uuid'] }}"
  with_items: osds['initialized']
  when: osds['initialized'] and osds is defined

- name: Gathering OSD IDs
  command: 'cat /var/lib/ceph/osd/{{ item.fs_uuid }}/whoami'
  with_items: osds['initialized']
  when: osds['initialized'] and osds is defined
  register: id
  changed_when: False
  failed_when: id.rc != 0
  always_run: True

- name: Starting Ceph OSD
  docker:
    name: "ceph_osd_{{ item.0.stdout }}"
    image: "{{ docker_registry }}/yaodu/ceph"
    state: "running"
    privileged: true
    pid: "host"
    net: "host"
    volumes: "/var/lib/ceph/osd/{{ item.1.fs_uuid }}:/var/lib/ceph/osd/{{ ceph_cluster_name }}-{{ item.0.stdout }},/opt/yaodu/ceph/:/etc/ceph/,/dev/:/dev/"
    env: "SERVICE=osd,CEPH_CLUSTER_NAME={{ ceph_cluster_name }},OSD_ID={{ item.0.stdout }}"
    command: "/entrypoint.sh"
  with_together:
    - id['results']
    - osds['initialized']
  when: osds['initialized'] and osds is defined
