FROM		{{ docker_registry }}/yaodu/common
MAINTAINER	Sam Yaple <sam@yaple.net>

RUN		apt-get install -y --no-install-recommends -t trusty-backports haproxy
RUN		apt-get clean -y

RUN		mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.org

ADD		entrypoint.sh /entrypoint.sh
RUN		chmod +x /entrypoint.sh

VOLUME          ["/etc/haproxy/haproxy.cfg"]
EXPOSE          3306
