---
- include: container_pull.yml
  vars:
    container: neutron

- name: Ensuring directories exist
  file:
    path: "{{ item }}"
    state: directory
    group: yaodu
    owner: yaodu
  with_items:
    - "/opt/yaodu/neutron/"
    - "/opt/yaodu/openvswitch/"
    - "/run/openvswitch/"

- name: Copying Neutron configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: yaodu
    owner: yaodu
    mode: 0644
  with_items:
    - { src: "neutron.conf.j2" , dest: "/opt/yaodu/neutron/neutron.conf" }
    - { src: "ml2_conf.ini.j2" , dest: "/opt/yaodu/neutron/ml2_conf.ini" }

- name: Creating keystone user neutron
  keystone:
    command: "ensure_user"
    tenant_name: "service"
    user_name: "neutron"
    password: "{{ keystone_neutron_password }}"
    description: "Neutron User"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Adding keystone role admin to user neutron
  keystone:
    command: "ensure_user_role"
    user_name: "neutron"
    tenant_name: "service"
    role_name: "admin"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Creating keystone service neutron
  keystone:
    command: "ensure_service"
    service_name: "neutron"
    service_type: "network"
    description: "Network Service"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Creating keystone endpoint neutron
  keystone:
    command: "ensure_endpoint"
    region_name: "regionOne"
    service_name: "neutron"
    service_type: "network"
    publicurl: "http://{{ yaodu_api_vip }}:9696"
    adminurl: "http://{{ yaodu_api_vip }}:9696"
    internalurl: "http://{{ yaodu_api_vip }}:9696"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Generating environment string
  docker_env_builder:
    config_files:
      - { src: "/opt/yaodu/neutron/neutron.conf", dest: "/etc/neutron/neutron.conf" }
      - { src: "/opt/yaodu/neutron/ml2_conf.ini", dest: "/etc/neutron/plugins/ml2/ml2_conf.ini" }
  register: docker_vars

- include: bootstrap.yml

- include: start.yml
