---
- include: container_pull.yml
  vars:
    container: neutron

- name: Ensuring directories exist
  file:
    path: "{{ item }}"
    state: directory
    group: yaodu
    owner: yaodu
  with_items:
    - "/opt/yaodu/neutron/"
    - "/opt/yaodu/openvswitch/"

- name: Creating default neutron files
  copy:
    directory_mode: yes
    src: "etc/neutron/"
    dest: "/opt/yaodu/neutron/"

- name: Copying Neutron configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "neutron.conf.j2" , dest: "/opt/yaodu/neutron/neutron.conf" }
    - { src: "ml2_conf.ini.j2" , dest: "/opt/yaodu/neutron/plugins/ml2/ml2_conf.ini" }

- name: Setting recursive owner for conf files
  file:
    path: "/opt/yaodu/neutron/"
    state: "directory"
    group: yaodu
    owner: yaodu
    recurse: "yes"

- name: Setting permissions for conf files and directories
  file:
    path: "{{ item.src }}"
    state: "{{ item.state }}"
    group: root
    owner: root
    recurse: "{{ item.recurse }}"
  with_items:
    - { src: "/opt/yaodu/neutron/rootwrap.conf", state: "file", recurse: "no" }
    - { src: "/opt/yaodu/neutron/rootwrap.d/", state: "directory", recurse: "yes"}

- name: Setting folder permissions
  file:
    path: "{{ item }}"
    state: "directory"
    mode: 0755
  with_items:
    - "/opt/yaodu/neutron/"
    - "/opt/yaodu/neutron/plugins/"
    - "/opt/yaodu/neutron/plugins/ml2/"
    - "/opt/yaodu/neutron/rootwrap.d/"

- name: Creating keystone user neutron
  keystone:
    command: "ensure_user"
    tenant_name: "service"
    user_name: "neutron"
    password: "{{ keystone_neutron_password }}"
    description: "Neutron User"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Adding keystone role admin to user neutron
  keystone:
    command: "ensure_user_role"
    user_name: "neutron"
    tenant_name: "service"
    role_name: "admin"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Creating keystone service neutron
  keystone:
    command: "ensure_service"
    service_name: "neutron"
    service_type: "network"
    description: "Network Service"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Creating keystone endpoint neutron
  keystone:
    command: "ensure_endpoint"
    region_name: "regionOne"
    service_name: "neutron"
    service_type: "network"
    publicurl: "http://{{ yaodu_api_vip }}:9696"
    adminurl: "http://{{ yaodu_api_vip }}:9696"
    internalurl: "http://{{ yaodu_api_vip }}:9696"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- include: bootstrap.yml

- include: start.yml
