---
- name: Starting neutron-server
  docker:
    name: "neutron-server"
    image: "{{ docker_registry }}/yaodu/neutron"
    state: "running"
    ports: "{{ ansible_br_mgmt['ipv4']['address'] }}:9696:9696"
    expose: "9696"
    volumes: "/opt/yaodu/neutron/:/etc/neutron/"
    env: "SERVICE=server"
    command: "/entrypoint.sh"
  when: inventory_hostname in groups['neutron-server']

- name: Starting neutron-l3-agent
  docker:
    name: "neutron-l3-agent"
    image: "{{ docker_registry }}/yaodu/neutron"
    state: "running"
    privileged: true
    net: host
    volumes: "/opt/yaodu/neutron/:/etc/neutron/,/var/run/netns/:/var/run/netns/"
    env: "SERVICE=l3-agent"
    command: "/entrypoint.sh"
  when: inventory_hostname in groups['neutron-agents']

- name: Starting neutron-dhcp-agent
  docker:
    name: "neutron-dhcp-agent"
    image: "{{ docker_registry }}/yaodu/neutron"
    state: "running"
    privileged: true
    net: host
    volumes: "/opt/yaodu/neutron/:/etc/neutron/,/var/run/netns/:/var/run/netns/"
    env: "SERVICE=dhcp-agent"
    command: "/entrypoint.sh"
  when: inventory_hostname in groups['neutron-agents']

- name: Starting openvswitch-db
  docker:
    name: "openvswitch-db"
    image: "{{ docker_registry }}/yaodu/neutron"
    state: "running"
    ports: "{{ ansible_br_mgmt['ipv4']['address'] }}:6633:6633"
    expose: "6633"
    volumes: "/opt/yaodu/openvswitch/:/etc/openvswitch/"
    env: "SERVICE=db"
    command: "/entrypoint.sh"
  when: inventory_hostname in groups['neutron-agents'] or
        inventory_hostname in groups['nova-compute']

- name: Starting openvswitch-switch
  docker:
    name: "openvswitch-switch"
    image: "{{ docker_registry }}/yaodu/neutron"
    state: "running"
    privileged: true
    net: host
    volumes: "/lib/modules/:/lib/modules/"
    env: "SERVICE=switch,REMOTE_IP={{ ansible_br_mgmt['ipv4']['address'] }}"
    command: "/entrypoint.sh"
  when: inventory_hostname in groups['neutron-agents'] or
        inventory_hostname in groups['nova-compute']

- name: Starting neutron-openvswitch-agent
  docker:
    name: "neutron-openvswitch-agent"
    image: "{{ docker_registry }}/yaodu/neutron"
    state: "running"
    privileged: true
    net: host
    volumes: "/opt/yaodu/neutron/:/etc/neutron/,/var/run/netns/:/var/run/netns/"
    env: "SERVICE=openvswitch-agent"
    command: "/entrypoint.sh"
  when: inventory_hostname in groups['neutron-agents'] or
        inventory_hostname in groups['nova-compute']
