---
- name: Starting openvswitch-db
  docker:
    name: "openvswitch-db"
    image: "{{ docker_registry }}/yaodu/neutron"
    state: "running"
    privileged: true
    net: "host"
    volumes: "/opt/yaodu/openvswitch/:/etc/openvswitch/,/run/:/run/"
    env: "SERVICE=db"
  when: inventory_hostname in groups['neutron-agent'] or
        inventory_hostname in groups['nova-compute']

- name: Starting openvswitch-switch
  docker:
    name: "openvswitch-switch"
    image: "{{ docker_registry }}/yaodu/neutron"
    state: "running"
    privileged: true
    net: "host"
    volumes: "/lib/modules/:/lib/modules/:ro,/run/:/run/"
    env: "SERVICE=switch,REMOTE_IP={{ ansible_br_mgmt['ipv4']['address'] }}"
  when: inventory_hostname in groups['neutron-agent'] or
        inventory_hostname in groups['nova-compute']

- name: Starting neutron-server
  docker:
    name: "neutron-server"
    image: "{{ docker_registry }}/yaodu/neutron"
    state: "running"
    net: "host"
    env: "{{ docker_vars.env }},SERVICE=server"
  when: inventory_hostname in groups['neutron-server']

- name: Starting neutron-l3-agent
  docker:
    name: "neutron-l3-agent"
    image: "{{ docker_registry }}/yaodu/neutron"
    state: "running"
    privileged: true
    net: "host"
    volumes: "/lib/modules/:/lib/modules/:ro,/run/:/run/,/proc/1/ns/:/opt/yaodu/host_proc/1/ns/:ro"
    env: "{{ docker_vars.env }},SERVICE=l3-agent"
  when: inventory_hostname in groups['neutron-agent']

- name: Starting neutron-dhcp-agent
  docker:
    name: "neutron-dhcp-agent"
    image: "{{ docker_registry }}/yaodu/neutron"
    state: "running"
    privileged: true
    net: "host"
    volumes: "/run/:/run/,/proc/1/ns/:/opt/yaodu/host_proc/1/ns/:ro"
    env: "{{ docker_vars.env }},SERVICE=dhcp-agent"
  when: inventory_hostname in groups['neutron-agent']

- name: setup bridge
  shell: docker exec -i -t openvswitch-switch sudo ovs-vsctl add-br br-ex || true
  when: inventory_hostname in groups['neutron-agent'] or
        inventory_hostname in groups['nova-compute']

- name: setup port
  shell: docker exec -i -t openvswitch-switch sudo ovs-vsctl add-port br-ex br-data || true
  when: inventory_hostname in groups['neutron-agent'] or
        inventory_hostname in groups['nova-compute']

- name: Starting neutron-openvswitch-agent
  docker:
    name: "neutron-openvswitch-agent"
    image: "{{ docker_registry }}/yaodu/neutron"
    state: "running"
    privileged: true
    net: "host"
    volumes: "/run/:/run/"
    env: "{{ docker_vars.env }},SERVICE=openvswitch-agent"
  when: inventory_hostname in groups['neutron-agent'] or
        inventory_hostname in groups['nova-compute']
