---
- include: check.yml
  vars:
    container: common
    templates:
      - { src: "{{ yaodu_distro }}/common/Dockerfile.j2", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/Dockerfile" }
      - { src: "{{ yaodu_distro }}/common/sources.list.j2", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/sources.list" }
      - { src: "{{ yaodu_distro }}/common/apt.conf.j2", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/apt.conf" }
