FROM		{{ docker_registry }}/yaodu/common
MAINTAINER	Sam Yaple <sam@yaple.net>

RUN		apt-get install -y --no-install-recommends ceph-common libvirt-bin dmidecode pm-utils qemu ebtables && \
                apt-get clean

ADD             sudoers /etc/sudoers.d/sudoers

ADD		kvm_bootstrap /opt/yaodu/kvm_bootstrap
RUN		chmod +x /opt/yaodu/kvm_bootstrap

ADD		entrypoint.sh /entrypoint.sh
RUN		chmod +x /entrypoint.sh

RUN             groupadd -g 42424 {{ container }} && useradd -u 42424 -g {{ container }} -s /sbin/nologin -c "{{ container }} user" {{ container }}
RUN             mkdir -p /var/log/{{ container }}/ /etc/{{ container }}/ /var/lib/{{ container }}/ /var/run/{{ container }}/ /var/lib/nova/instances/ && \
                chown -R {{ container }}: /var/log/{{ container }}/ /etc/{{ container }}/ /var/lib/{{ container }}/ /var/run/{{ container }}/ /var/lib/nova/instances/

USER            {{ container }}
WORKDIR         /var/lib/{{ container }}/
