FROM		{{ docker_registry }}/yaodu/common
MAINTAINER	Sam Yaple <sam@yaple.net>

RUN             apt-get install -y --no-install-recommends mariadb-galera-server percona-xtrabackup socat expect && \
                apt-get clean

ADD		entrypoint.sh /entrypoint.sh
RUN		chmod +x /entrypoint.sh

RUN             groupmod -g 42424 mysql && usermod -u 42424 mysql
RUN             chown -R mysql: /var/log/mysql/ /etc/mysql/ /var/run/mysqld/

USER            mysql
WORKDIR         /var/lib/mysql/
ENTRYPOINT      ["/entrypoint.sh"]
