---
- name: Ensuring the latest version of base image exists locally
  command: "docker pull {{ yaodu_distro }}:{{ yaodu_distro_tag }}"
  async: 600
  poll: 5
  run_once: True
  when: forced

- include: check.yml
  vars:
    container: common
    templates:
      - { src: "{{ yaodu_distro }}/common/Dockerfile.j2", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/Dockerfile" }
      - { src: "{{ yaodu_distro }}/common/sources.list.j2", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/sources.list" }
      - { src: "{{ yaodu_distro }}/common/apt.conf.j2", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/apt.conf" }
      - { src: "{{ yaodu_distro }}/common/mariadb.list.j2", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/mariadb.list" }
      - { src: "{{ yaodu_distro }}/common/rabbitmq.list.j2", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/rabbitmq.list" }
      - { src: "{{ yaodu_distro }}/common/ceph.list.j2", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/ceph.list" }
      - { src: "{{ yaodu_distro }}/common/percona.list.j2", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/percona.list" }
    files:
      - { src: "errors.sh", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/errors.sh" }
      - { src: "common.sh", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/common.sh" }
      - { src: "env_parser.py", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/env_parser.py" }
