---
- include: common.yml
  tags: common

- include: ceph.yml
  tags: ceph

- include: mariadb.yml
  tags: mariadb

- include: rabbitmq.yml
  tags: rabbitmq

- include: haproxy.yml
  tags: haproxy

- include: keepalived.yml
  tags: keepalived

- include: libvirt.yml
  tags: libvirt

- include: openstack_common.yml
  tags: openstack_common

- include: keystone.yml
  tags: keystone

- include: glance.yml
  tags: glance

- include: nova.yml
  tags: nova

- include: neutron.yml
  tags: neutron

- include: cinder.yml
  tags: cinder
