---
- include: check.yml
  vars:
    container: neutron
    templates:
      - { src: "{{ yaodu_distro }}/{{ container }}/Dockerfile.j2", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/Dockerfile" }
    files:
      - { src: "{{ yaodu_distro }}/{{ container }}/entrypoint.sh", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/entrypoint.sh" }
    web_files:
        - { src: "http://tarballs.openstack.org/{{ container }}/{{ container }}-{{ openstack_revision }}.tar.gz", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/{{ container }}.tar.gz" }
