---
- include: check.yml
  vars:
    container: openstack_common
    templates:
      - { src: "{{ yaodu_distro }}/{{ container }}/Dockerfile.j2", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/Dockerfile" }
      - { src: "{{ yaodu_distro }}/{{ container }}/juno.list.j2", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/juno.list" }
