---
- include: container_pull.yml

- name: Ensuring /opt/yaodu/nova/ exists
  file:
    path: /opt/yaodu/nova/
    state: directory

- name: Copying Nova configs
  template:
    src: "nova.conf.j2"
    dest: "/opt/yaodu/nova/nova.conf"
    group: yaodu
    owner: yaodu
    mode: 0644

- name: Creating keystone user nova
  keystone:
    command: "ensure_user"
    tenant_name: "service"
    user_name: "nova"
    password: "{{ keystone_nova_password }}"
    description: "Nova User"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Adding keystone role admin to user nova
  keystone:
    command: "ensure_user_role"
    tenant_name: "service"
    user_name: "nova"
    role_name: "admin"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Creating keystone service nova
  keystone:
    command: "ensure_service"
    service_name: "nova"
    service_type: "compute"
    description: "Compute Service"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Creating keystone endpoint nova
  keystone:
    command: "ensure_endpoint"
    region_name: "regionOne"
    service_name: "nova"
    service_type: "compute"
    publicurl: "http://{{ yaodu_api_vip }}:8774/v2/%(tenant_id)s"
    adminurl: "http://{{ yaodu_api_vip }}:8774/v2/%(tenant_id)s"
    internalurl: "http://{{ yaodu_api_vip }}:8774/v2/%(tenant_id)s"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Creating keystone service novav3
  keystone:
    command: "ensure_service"
    service_name: "novav3"
    service_type: "computev3"
    description: "Compute Service"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Creating keystone endpoint novav3
  keystone:
    command: "ensure_endpoint"
    region_name: "regionOne"
    service_name: "novav3"
    service_type: "computev3"
    publicurl: "http://{{ yaodu_api_vip }}:8774/v3"
    adminurl: "http://{{ yaodu_api_vip }}:8774/v3"
    internalurl: "http://{{ yaodu_api_vip }}:8774/v3"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Generating environment string
  docker_env_builder:
    config_files:
      - { src: '/opt/yaodu/nova/nova.conf', dest: '/etc/nova/nova.conf' }
  register: docker_vars

- include: bootstrap.yml

- include: start.yml
