---
- include: container_pull.yml
  vars:
    container: nova

- name: Ensuring /opt/yaodu/nova/ exists
  file:
    path: /opt/yaodu/nova/
    state: directory

- name: Creating default nova files
  copy:
    directory_mode: yes
    src: "etc/nova/"
    dest: "/opt/yaodu/nova/"

- name: Copying Nova configs
  template:
    src: "nova.conf.j2"
    dest: "/opt/yaodu/nova/nova.conf"

- name: Setting recursive owner for conf files
  file:
    path: "/opt/yaodu/nova/"
    state: "directory"
    group: yaodu
    owner: yaodu
    recurse: "yes"

- name: Setting permissions for conf files and directories
  file:
    path: "{{ item.src }}"
    state: "{{ item.state }}"
    group: root
    owner: root
    recurse: "{{ item.recurse }}"
  with_items:
    - { src: "/opt/yaodu/nova/rootwrap.conf", state: "file", recurse: "no" }
    - { src: "/opt/yaodu/nova/rootwrap.d/", state: "directory", recurse: "yes" }

- name: Setting folder permissions
  file:
    path: "{{ item }}"
    state: "directory"
    mode: 0755
  with_items:
    - "/opt/yaodu/nova/"
    - "/opt/yaodu/nova/rootwrap.d/"

- name: Creating keystone user nova
  keystone:
    command: "ensure_user"
    tenant_name: "service"
    user_name: "nova"
    password: "{{ keystone_nova_password }}"
    description: "Nova User"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Adding keystone role admin to user nova
  keystone:
    command: "ensure_user_role"
    tenant_name: "service"
    user_name: "nova"
    role_name: "admin"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Creating keystone service nova
  keystone:
    command: "ensure_service"
    service_name: "nova"
    service_type: "compute"
    description: "Compute Service"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Creating keystone endpoint nova
  keystone:
    command: "ensure_endpoint"
    region_name: "regionOne"
    service_name: "nova"
    service_type: "compute"
    publicurl: "http://{{ yaodu_api_vip }}:8774/v2/%(tenant_id)s"
    adminurl: "http://{{ yaodu_api_vip }}:8774/v2/%(tenant_id)s"
    internalurl: "http://{{ yaodu_api_vip }}:8774/v2/%(tenant_id)s"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Creating keystone service novav3
  keystone:
    command: "ensure_service"
    service_name: "novav3"
    service_type: "computev3"
    description: "Compute Service"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Creating keystone endpoint novav3
  keystone:
    command: "ensure_endpoint"
    region_name: "regionOne"
    service_name: "novav3"
    service_type: "computev3"
    publicurl: "http://{{ yaodu_api_vip }}:8774/v3"
    adminurl: "http://{{ yaodu_api_vip }}:8774/v3"
    internalurl: "http://{{ yaodu_api_vip }}:8774/v3"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- include: bootstrap.yml

- include: start.yml
