---
- include: container_pull.yml
  vars:
    container: nova

- name: Ensuring /opt/yaodu/nova/ exists
  file:
    path: /opt/yaodu/nova/
    state: directory
    group: yaodu
    owner: yaodu

- name: Creating default nova files
  copy:
    directory_mode: yes
    src: "etc/nova/"
    dest: "/opt/yaodu/nova/"
    group: yaodu
    owner: yaodu

- name: Copying Nova configs
  template:
    src: "nova.conf.j2"
    dest: "nova.conf"
    mode: 0644
    group: yaodu
    owner: yaodu

- name: Getting Cephx Cinder key
  shell: ceph auth get-or-create client.cinder
  register: cephx_key
  run_once: True

- name: Setting Cephx Cinder key
  copy:
    content: "{{ cephx_key.stdout }}\n\r"
    dest: "/opt/yaodu/cinder/ceph.client.cinder.keyring"
    group: yaodu
    owner: yaodu

- name: Creating keystone user nova
  keystone:
    command: "ensure_user"
    tenant_name: "service"
    user_name: "nova"
    password: "{{ keystone_nova_password }}"
    description: "Nova User"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Adding keystone role admin to user nova
  keystone:
    command: "ensure_user_role"
    tenant_name: "service"
    user_name: "nova"
    role_name: "admin"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Creating keystone service nova
  keystone:
    command: "ensure_service"
    service_name: "nova"
    service_type: "compue"
    description: "Compute Service"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Creating keystone endpoint nova
  keystone:
    command: "ensure_endpoint"
    region_name: "regionOne"
    service_name: "nova"
    service_type: "compue"
    publicurl: "http://{{ yaodu_api_vip }}:8774/v2/%(tenant_id)s"
    adminurl: "http://{{ yaodu_api_vip }}:8774/v2/%(tenant_id)s"
    internalurl: "http://{{ yaodu_api_vip }}:8774/v2/%(tenant_id)s"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- include: bootstrap.yml

- include: start.yml
