---
- name: Starting nova-api
  docker:
    name: "nova-api"
    image: "{{ docker_registry }}/yaodu/nova"
    state: "running"
    privileged: true
    net: "host"
    volumes: "/opt/yaodu/nova/:/etc/nova/"
    env: "SERVICE=api"
    command: "/entrypoint.sh"
  when: inventory_hostname in groups['nova']

- name: Starting nova-scheduler
  docker:
    name: "nova-scheduler"
    image: "{{ docker_registry }}/yaodu/nova"
    state: "running"
    net: "host"
    volumes: "/opt/yaodu/nova/:/etc/nova/"
    env: "SERVICE=scheduler"
    command: "/entrypoint.sh"
  when: inventory_hostname in groups['nova']

- name: Starting nova-conductor
  docker:
    name: "nova-conductor"
    image: "{{ docker_registry }}/yaodu/nova"
    state: "running"
    net: "host"
    volumes: "/opt/yaodu/nova/:/etc/nova/"
    env: "SERVICE=conductor"
    command: "/entrypoint.sh"
  when: inventory_hostname in groups['nova']

- name: Starting nova-console
  docker:
    name: "nova-console"
    image: "{{ docker_registry }}/yaodu/nova"
    state: "running"
    net: "host"
    volumes: "/opt/yaodu/nova/:/etc/nova/"
    env: "SERVICE=console"
    command: "/entrypoint.sh"
  when: inventory_hostname in groups['nova']

- name: Starting nova-consoleauth
  docker:
    name: "nova-consoleauth"
    image: "{{ docker_registry }}/yaodu/nova"
    state: "running"
    net: "host"
    volumes: "/opt/yaodu/nova/:/etc/nova/"
    env: "SERVICE=consoleauth"
    command: "/entrypoint.sh"
  when: inventory_hostname in groups['nova']

- name: Starting nova-spicehtml5proxy
  docker:
    name: "nova-spicehtml5proxy"
    image: "{{ docker_registry }}/yaodu/nova"
    state: "running"
    net: "host"
    volumes: "/opt/yaodu/nova/:/etc/nova/"
    env: "SERVICE=spicehtml5proxy"
    command: "/entrypoint.sh"
  when: inventory_hostname in groups['nova']

- name: Starting nova-compute
  docker:
    name: "nova-compute"
    image: "{{ docker_registry }}/yaodu/nova"
    state: "running"
    privileged: true
    net: "host"
    volumes: "/opt/yaodu/nova/:/etc/nova/,/opt/yaodu/libvirt/instances/:/var/lib/nova/instances/,/opt/yaodu/ceph/{{ ceph_cluster_name }}.conf:/etc/ceph/{{ ceph_cluster_name }}.conf:ro,/opt/yaodu/ceph/{{ ceph_cluster_name }}.client.nova.keyring:/etc/ceph/{{ ceph_cluster_name }}.client.nova.keyring:ro,/run/:/run/"
    env: "SERVICE=compute"
    command: "/entrypoint.sh"
  when: inventory_hostname in groups['nova-compute']
