---
- name: Starting nova-api
  docker:
    name: "nova-api"
    image: "{{ docker_registry }}/yaodu/nova"
    state: "running"
    privileged: true
    ports: "{{ ansible_br_mgmt['ipv4']['address'] }}:8773:8773,{{ ansible_br_mgmt['ipv4']['address'] }}:8774:8774,{{ ansible_br_mgmt['ipv4']['address'] }}:8775:8775"
    expose: "8773,8774,8775"
    volumes: "/opt/yaodu/nova/:/etc/nova/"
    env: "SERVICE=api"
    command: "/entrypoint.sh"
  when: inventory_hostname in groups['nova']

- name: Starting nova-scheduler
  docker:
    name: "nova-scheduler"
    image: "{{ docker_registry }}/yaodu/nova"
    state: "running"
    volumes: "/opt/yaodu/nova/:/etc/nova/"
    hostname: "{{ ansible_hostname }}-nova"
    env: "SERVICE=scheduler"
    command: "/entrypoint.sh"
  when: inventory_hostname in groups['nova']

- name: Starting nova-conductor
  docker:
    name: "nova-conductor"
    image: "{{ docker_registry }}/yaodu/nova"
    state: "running"
    volumes: "/opt/yaodu/nova/:/etc/nova/"
    hostname: "{{ ansible_hostname }}-nova"
    env: "SERVICE=conductor"
    command: "/entrypoint.sh"
  when: inventory_hostname in groups['nova']

- name: Starting nova-console
  docker:
    name: "nova-console"
    image: "{{ docker_registry }}/yaodu/nova"
    state: "running"
    volumes: "/opt/yaodu/nova/:/etc/nova/"
    hostname: "{{ ansible_hostname }}-nova"
    env: "SERVICE=console"
    command: "/entrypoint.sh"
  when: inventory_hostname in groups['nova']

- name: Starting nova-consoleauth
  docker:
    name: "nova-consoleauth"
    image: "{{ docker_registry }}/yaodu/nova"
    state: "running"
    volumes: "/opt/yaodu/nova/:/etc/nova/"
    hostname: "{{ ansible_hostname }}-nova"
    env: "SERVICE=consoleauth"
    command: "/entrypoint.sh"
  when: inventory_hostname in groups['nova']

- name: Starting nova-spicehtml5proxy
  docker:
    name: "nova-spicehtml5proxy"
    image: "{{ docker_registry }}/yaodu/nova"
    state: "running"
    ports: "{{ ansible_br_mgmt['ipv4']['address'] }}:6082:6082"
    expose: "6082"
    volumes: "/opt/yaodu/nova/:/etc/nova/"
    env: "SERVICE=spicehtml5proxy"
    command: "/entrypoint.sh"
  when: inventory_hostname in groups['nova']

- name: Starting nova-compute
  docker:
    name: "nova-compute"
    image: "{{ docker_registry }}/yaodu/nova"
    state: "running"
    volumes: "/opt/yaodu/nova/:/etc/nova/,/opt/yaodu/nova/ceph.conf:/etc/ceph/ceph.conf,/opt/yaodu/nova/ceph.client.cinder.keyring:/etc/ceph/ceph.client.cinder.keyring"
    hostname: "{{ ansible_hostname }}-nova"
    env: "SERVICE=compute"
    command: "/entrypoint.sh"
  when: inventory_hostname in groups['nova-compute']
