---
- name: Add the Docker repository key to keychain
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: Add the Docker repository to apt sources
  apt_repository:
    repo: 'deb http://get.docker.com/ubuntu docker main'

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - lxc-docker
    - python-pip
