---
- name: Starting RabbitMQ
  docker:
    docker_api_version: '1.18'
    name: "rabbitmq"
    image: "{{ docker_registry }}/yaodu/rabbitmq"
    state: "running"
    net: "host"
    volumes: "/opt/yaodu/rabbitmq/:/var/lib/rabbitmq/,/opt/yaodu/rabbitmq/rabbitmq-env.conf:/etc/rabbitmq/rabbitmq-env.conf"
    hostname: "{{ ansible_hostname }}"
