---
- name: Ensuring Docker image yaodu/{{ container }} exists locally
  docker_image_check:
    image: "yaodu/{{ container }}"
    registry: "{{ docker_registry }}"
    protocol: "http"
    insecure_registry: True
    compare: True
  register: docker_image_info

- name: Pulling latest image
  command: docker pull "{{ docker_registry }}/yaodu/{{ container }}"
  async: 600
  poll: 5
  when: forced or not docker_image_info.image.local_up_to_date
