---
- include: check.yml
  vars:
    container: ceph
    templates:
      - { src: "{{ yaodu_distro }}/{{ container }}/Dockerfile.j2", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/Dockerfile" }
      - { src: "{{ yaodu_distro }}/{{ container }}/ceph.list.j2", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/ceph.list" }
      - { src: "{{ yaodu_distro }}/{{ container }}/mon.sh.j2", dest: "{{ yaodu_directory }}/{{ yaodu_distro }}/{{ container }}/mon.sh" }
