---
- include: container_pull.yml
  vars:
    container: haproxy

- name: Ensuring /opt/yaodu/mariadb/data/ exists
  file:
    path: /opt/yaodu/haproxy/
    state: directory
    group: yaodu
    owner: yaodu

- name: Copying haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: "/opt/yaodu/haproxy/haproxy.cfg"
    mode: 0644

- name: Allowing non-local IP binding
  sysctl: name="net.ipv4.ip_nonlocal_bind" value=1 sysctl_set=yes

- include: start.yml
