---
- name: Starting haproxy
  docker:
    docker_api_version: '1.18'
    name: "haproxy"
    image: "{{ docker_registry }}/yaodu/haproxy"
    state: "running"
    net: "host"
    volumes: "/opt/yaodu/haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg"
