FROM		{{ yaodu_distro }}:{{ yaodu_distro_tag }}
MAINTAINER	Sam Yaple <sam@yaple.net>

ENV		DEBIAN_FRONTEND	noninteractive

# Recommend apt-cacher-ng for bandwidth savings. Not required.
ADD		apt.conf /etc/apt/apt.conf
ADD		sources.list /etc/apt/sources.list

RUN		apt-get update && apt-get dist-upgrade -y && \
		apt-get install -y --no-install-recommends curl ca-certificates && \
                apt-get clean -y

ADD             errors.sh /opt/yaodu/errors.sh
