FROM		{{ docker_registry }}/yaodu/openstack_common
MAINTAINER	Sam Yaple <sam@yaple.net>

RUN		apt-get install -y keystone && \
                apt-get clean

RUN             mv /etc/keystone /etc/keystone.org

ADD             entrypoint.sh /entrypoint.sh
RUN             chmod +x /entrypoint.sh

USER            keystone
WORKDIR         /var/lib/keystone
