FROM		{{ docker_registry }}/yaodu/openstack_common
MAINTAINER	Sam Yaple <sam@yaple.net>

RUN		apt-get install -y --no-install-recommends nova-api nova-scheduler nova-conductor nova-cert nova-console nova-consoleauth && \
                apt-get clean

RUN             mv /etc/nova/ /etc/nova.org/

ADD             entrypoint.sh /entrypoint.sh
RUN             chmod +x /entrypoint.sh

USER            nova
WORKDIR         /var/lib/nova
