FROM		{{ docker_registry }}/yaodu/openstack_common
MAINTAINER	Sam Yaple <sam@yaple.net>

ADD             {{ container }}.tar.gz /opt/yaodu/
RUN             ln -s /opt/yaodu/{{ container }}-*/ /opt/yaodu/{{ container }}

ADD             novnc.tar.gz /opt/yaodu/
RUN             ln -s /opt/yaodu/kanaka-noVNC-*/ /usr/share/novnc

ADD             spice-html5.tar.gz /opt/yaodu/
RUN             ln -s /opt/yaodu/SPICE-spice-html5-*/ /usr/share/spice-html5

RUN             apt-get install -y --no-install-recommends ceph-common iptables ebtables dnsmasq bridge-utils python-libvirt openssh-client openvswitch-switch && apt-get clean

RUN             cd /opt/yaodu/requirements/ && python update.py /opt/yaodu/{{ container }}/
RUN             cd /opt/yaodu/{{ container }}/ && pip install .

ADD             sudoers /etc/sudoers.d/sudoers

ADD             entrypoint.sh /entrypoint.sh
RUN             chmod +x /entrypoint.sh

RUN             groupadd -g 42424 {{ container }} && useradd -u 42424 -g {{ container }} -s /sbin/nologin -c "{{ container }} user" {{ container }}
RUN             mkdir -p /etc/ceph/ /var/log/{{ container }}/ /var/lib/{{ container }}/ && \
                chown -R {{ container }}: /etc/ceph/ /var/log/{{ container }}/ /var/lib/{{ container }}/

USER            {{ container }}
WORKDIR         /var/lib/{{ container }}
ENTRYPOINT      ["/entrypoint.sh"]
