FROM		{{ docker_registry }}/yaodu/common
MAINTAINER	Sam Yaple <sam@yaple.net>

RUN		apt-get install -y --no-install-recommends openvswitch-switch && \
                apt-get clean

ADD		entrypoint.sh /entrypoint.sh
RUN		chmod +x /entrypoint.sh

RUN             groupadd -g 42424 {{ container }} && useradd -u 42424 -g {{ container }} -s /sbin/nologin -c "{{ container }} user" {{ container }}
RUN             chown -R {{ container }}: /var/log/{{ container }}/ /etc/{{ container }}/

USER            {{ container }}
WORKDIR         /var/lib/{{ container }}/
