---
- include: container_pull.yml
  vars:
    container: cinder

- name: Ensuring /opt/yaodu/cinder/ exists
  file:
    path: /opt/yaodu/cinder/
    state: directory
    group: yaodu
    owner: yaodu

- name: Creating default cinder files
  copy:
    directory_mode: yes
    src: "etc/cinder/"
    dest: "/opt/yaodu/cinder/"
    group: yaodu
    owner: yaodu

- name: Copying Cinder configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    group: yaodu
    owner: yaodu
  with_items:
    - { src: "cinder.conf.j2" , dest: "/opt/yaodu/cinder/cinder.conf" }
    - { src: "ceph.conf.j2" , dest: "/opt/yaodu/cinder/ceph.conf" }

- name: Getting Cephx Cinder key
  shell: ceph auth get-or-create client.cinder
  register: cephx_key
  run_once: True

- name: Setting Cephx Cinder key
  copy:
    content: "{{ cephx_key.stdout }}\n\r"
    dest: "/opt/yaodu/cinder/ceph.client.cinder.keyring"
    group: yaodu
    owner: yaodu

- name: Creating keystone user cinder
  keystone:
    command: "ensure_user"
    tenant_name: "service"
    user_name: "cinder"
    password: "{{ keystone_cinder_password }}"
    description: "Cinder User"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Adding keystone role admin to user cinder
  keystone:
    command: "ensure_user_role"
    tenant_name: "service"
    user_name: "cinder"
    role_name: "admin"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Creating keystone service cinder
  keystone:
    command: "ensure_service"
    service_name: "cinder"
    service_type: "volumev2"
    description: "Block Storage Service"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- name: Creating keystone endpoint cinder
  keystone:
    command: "ensure_endpoint"
    region_name: "regionOne"
    service_name: "cinder"
    service_type: "volumev2"
    publicurl: "http://{{ yaodu_api_vip }}:8776/v2/%(tenant_id)s"
    adminurl: "http://{{ yaodu_api_vip }}:8776/v2/%(tenant_id)s"
    internalurl: "http://{{ yaodu_api_vip }}:8776/v2/%(tenant_id)s"
    endpoint: "http://{{ yaodu_api_vip }}:35357/v2.0"
    login_user: "admin"
    login_password: "{{ keystone_admin_password }}"
    login_tenant_name: "admin"
  run_once: True

- include: bootstrap.yml

- include: start.yml
