---
- name: Starting Cinder Api
  docker:
    name: "cinder-api"
    image: "{{ docker_registry }}/yaodu/cinder"
    state: "running"
    net: "host"
    env: "{{ docker_vars.env}},SERVICE=api"

- name: Starting Cinder Scheduler
  docker:
    name: "cinder-scheduler"
    image: "{{ docker_registry }}/yaodu/cinder"
    state: "running"
    net: "host"
    env: "{{ docker_vars.env}},SERVICE=scheduler"

- name: Starting Cinder Volume
  docker:
    name: "cinder-volume"
    image: "{{ docker_registry }}/yaodu/cinder"
    state: "running"
    net: "host"
    volumes: "/opt/yaodu/ceph/{{ ceph_cluster_name }}.conf:/etc/ceph/{{ ceph_cluster_name }}.conf:ro,/opt/yaodu/ceph/{{ ceph_cluster_name }}.client.cinder.keyring:/etc/ceph/{{ ceph_cluster_name }}.client.cinder.keyring:ro"
    hostname: "cinder-volume"
    env: "{{ docker_vars.env}},SERVICE=volume"
