---
- name: Starting Cinder Api
  docker:
    name: "cinder-api"
    image: "{{ docker_registry }}/yaodu/cinder"
    state: "running"
    net: "host"
    volumes: "/opt/yaodu/cinder/:/etc/cinder/"
    env: "SERVICE=api"
    command: "/entrypoint.sh"

- name: Starting Cinder Scheduler
  docker:
    name: "cinder-scheduler"
    image: "{{ docker_registry }}/yaodu/cinder"
    state: "running"
    net: "host"
    volumes: "/opt/yaodu/cinder/:/etc/cinder/"
    env: "SERVICE=scheduler"
    command: "/entrypoint.sh"

- name: Starting Cinder Volume
  docker:
    name: "cinder-volume"
    image: "{{ docker_registry }}/yaodu/cinder"
    state: "running"
    net: "host"
    volumes: "/opt/yaodu/cinder/:/etc/cinder/,/opt/yaodu/ceph/{{ ceph_cluster_name }}.conf:/etc/ceph/{{ ceph_cluster_name }}.conf:ro,/opt/yaodu/ceph/{{ ceph_cluster_name }}.client.cinder.keyring:/etc/ceph/{{ ceph_cluster_name }}.client.cinder.keyring:ro"
    hostname: "cinder-volume"
    env: "SERVICE=volume"
    command: "/entrypoint.sh"

