FROM		{{ docker_registry }}/yaodu/common
MAINTAINER	Sam Yaple <sam@yaple.net>

RUN		apt-get install -y python-pip python-dev python-mysqldb libmysqlclient-dev libxslt1-dev libpq-dev libffi-dev libyaml-dev pkg-config && \
                apt-get clean

RUN             pip install --upgrade wheel cython

ADD             openstack-requirements.tar /opt/yaodu/
RUN             ln -s /opt/yaodu/openstack-requirements-*/ /opt/yaodu/requirements

RUN             awk '/^python-.*client/ {print $1}' /opt/yaodu/requirements/global-requirements.txt | xargs pip install --upgrade
