FROM		{{ docker_registry }}/yaodu/common
MAINTAINER	Sam Yaple <sam@yaple.net>

RUN		apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com 391A9AA2147192839E9DB0315EDB1B62EC4926EA
ADD             juno.list /etc/apt/sources.list.d/juno.list

RUN		apt-get update && \
                apt-get dist-upgrade -y && \
                apt-get install -y python-cinderclient python-glanceclient python-keystoneclient python-neutronclient python-novaclient python-swiftclient \
                                   alembic python-mysqldb python-oslo.messaging python-oslo.db python-oslo.rootwrap python-oslo.serialization && \
                apt-get clean
