---
- hosts: all
  roles:
    - base

#- hosts: docker-registry
#  tasks:
#  - name: Removing temporary Docker registry
#    docker:
#      image: registry
#      name: tmp_registry
#      state: absent
#    tags: purge
#  - name: Starting temporary Docker registry
#    docker:
#      image: registry
#      ports: "{{ docker_tmp_registry_port | default('4001') }}:5000"
#      name: tmp_registry
#      env: "{{ docker_registry_env_vars | default('GUNICORN_OPTS=[--preload]') }}"
#    run_once: true

- hosts: build-hosts
  roles:
    - docker_build
  tags: build

- hosts:
    - management
    - ceph-all
    - compute
  roles:
    - ceph
  tags: ceph

- hosts:
    - management
    - database
  roles:
    - mariadb
  tags: database

- hosts: load-balancer
  roles:
    - keepalived
    - haproxy
  tags:
    - keepalived
    - haproxy

- hosts: message-broker
  roles:
    - rabbitmq
  tags: rabbitmq

- hosts: keystone
  roles:
    - keystone
  tags: keystone
