---
- hosts: all
  roles:
    - base

#- hosts: docker-registry
#  tasks:
#  - name: Removing temporary Docker registry
#    docker:
#      image: registry
#      name: tmp_registry
#      state: absent
#    tags: purge
#  - name: Starting temporary Docker registry
#    docker:
#      image: registry
#      ports: "{{ docker_tmp_registry_port | default('4001') }}:5000"
#      name: tmp_registry
#      env: "{{ docker_registry_env_vars | default('GUNICORN_OPTS=[--preload]') }}"
#    run_once: true

- hosts: build-hosts
  roles:
    - docker_build/common
    - docker_build/openstack_common
    - docker_build/ceph
    - docker_build/mariadb
  tags: build

- hosts:
    - management
    - ceph-all
    - compute
  roles:
    - ceph

- hosts: database
  roles:
    - mariadb
  tags: database
