---
- hosts: all
  roles:
    - common

#- hosts: docker-registry
#  tasks:
#  - name: Removing temporary Docker registry
#    docker:
#      image: registry
#      name: tmp_registry
#      state: absent
#    tags: purge
#  - name: Starting temporary Docker registry
#    docker:
#      image: registry
#      ports: "{{ docker_tmp_registry_port | default('4001') }}:5000"
#      name: tmp_registry
#      env: "{{ docker_registry_env_vars | default('GUNICORN_OPTS=[--preload]') }}"
#    run_once: true

- hosts: build_host
  roles:
    - docker_build/base
    - docker_build/common
    - docker_build/openstack_common
    - docker_build/ceph

- hosts: ceph-all
  roles:
    - ceph/common
  tags: test

- hosts: ceph-mon
  roles:
    - ceph/mon
