---
- hosts: all
  roles:
    - base
  tags: base

- hosts:
    - management
    - ceph-all
    - compute
  roles:
    - ceph
  tags: ceph

- hosts:
    - management
    - database
  roles:
    - mariadb
  tags: mariadb

- hosts: load-balancer
  roles:
    - keepalived
    - haproxy
  tags:
    - keepalived
    - haproxy

- hosts: message-broker
  roles:
    - rabbitmq
  tags: rabbitmq

- hosts: keystone
  roles:
    - keystone
  tags: keystone

- hosts: glance
  roles:
    - glance
  tags: glance

- hosts: cinder
  roles:
    - cinder
  tags: cinder

- hosts: nova
  roles:
    - nova
  tags: nova

- hosts:
    - neutron-server
    - neutron-agents
  roles:
      - neutron
  tags: neutron
