---
- include: container_pull.yml
  vars:
    container: keepalived

- name: Ensuring /opt/yaodu/mariadb/data/ exists
  file:
    path: /opt/yaodu/keepalived/
    state: directory
    group: yaodu
    owner: yaodu

- name: Copying keepalived.conf
  template:
    src: keepalived.conf.j2
    dest: "/opt/yaodu/keepalived/keepalived.conf"
    mode: 0644

- include: start.yml
