---
- name: Starting keepalived
  docker:
    docker_api_version: '1.18'
    name: "keepalived"
    image: "{{ docker_registry }}/yaodu/keepalived"
    state: "running"
    privileged: "True"
    net: "host"
    volumes: "/opt/yaodu/keepalived/keepalived.conf:/etc/keepalived/keepalived.conf,/lib/modules/:/lib/modules/"
