FROM		{{ docker_registry  }}/yaodu/common
MAINTAINER	Sam Yaple <sam@yaple.net>

RUN             apt-get install -y --no-install-recommends ceph parted hdparm && \
                apt-get clean

ADD		entrypoint.sh /entrypoint.sh
RUN		chmod +x /entrypoint.sh
ENTRYPOINT      ["/entrypoint.sh"]
