---
- name: Ensuring we have the latest container
  docker_image_check:
    image: "yaodu/{{ container }}"
    registry: "{{ docker_registry  }}"
    tag: "{{ tag }}"
  when: run

- name: Bootstraping Ceph Mon
  docker:
    net: host
    volumes: /etc/ceph:/etc/ceph
    state: running
    image: "{{ docker_registry  }}/yaodu/ceph"
    env: "INITIAL_CLUSTER=true,MON_NAME={{ ansible_hostname }},MON_IP={{ ansible_br_stor['ipv4']['address'] }}"
    command: "/opt/ceph/mon.sh"
    name: "ceph_mon"
  run_once: true

- name: Reloading Ceph Mons
  docker:
    net: host
    volumes: /etc/ceph:/etc/ceph
    state: running
    image: "{{ docker_registry  }}/yaodu/ceph"
    env: "MON_NAME={{ ansible_hostname }},MON_IP={{ ansible_br_stor['ipv4']['address'] }}"
    command: "/opt/ceph/mon.sh"
    name: "ceph_mon"
