FROM		{{ docker_registry }}/yaodu/common
MAINTAINER	Sam Yaple <sam@yaple.net>

RUN		apt-get install -y --no-install-recommends rabbitmq-server && \
                apt-get clean

ADD		entrypoint.sh /entrypoint.sh
RUN		chmod +x /entrypoint.sh

RUN             groupmod -g 42424 rabbitmq && usermod -u 42424 rabbitmq
RUN             chown -R rabbitmq: /var/log/rabbitmq/ /etc/rabbitmq/

USER            rabbitmq
WORKDIR         /var/lib/rabbitmq/
